CREATE ROLE vk WITH LOGIN PASSWORD '12345';
ALTER ROLE vk WITH SUPERUSER;
CREATE DATABASE monitoring_docker OWNER vk;
CREATE USER vk WITH PASSWORD '12345';
GRANT ALL PRIVILEGES ON DATABASE monitoring_docker TO vk;