CREATE TABLE IF NOT EXISTS ips (
    id SERIAL PRIMARY KEY,
    ip VARCHAR(100),
    ping_time INTEGER,
    last_ok TIMESTAMP
);

CREATE USER vk WITH PASSWORD '12345';
GRANT ALL PRIVILEGES ON DATABASE monitoring TO vk;
